# Skye Goetz (ISB) 09/11/2024

# FILE MUST BE ".yml" TO BE RECOGNIZED BY TABLASSERT

knowledge_graph_name : # <Name of the Final Knowledge Graph>
ploverize_graph : # <yes/no About Whether to Make the Graph Plover Compatible>
max_workers : # <Number of Workers To Run in Parallel>
p_value_cutoff : # <Float of Maximum Knowledge Graph P-Value>
re_nice : # <Integer of Value to Nice All Processes By>

config_directories:
 - # <List of>
 - # <All Directories>
 - # <Containing .yml>
 - # <Table Configs>

DB_map : # <Path to SQLite3 Map Database>
DB_res : # <Path to SQLite3 Resolver Database>
DB_pref : # <Path to SQLite3 Preferred Names Database>
DB_hash : # <Path to SQLite3 Hashed Revolver Database>

# SQLite3 DB Requirements...
# Map DB : TABLE: "MAP" SCHEMA: | "ALIAS" | "PREFERRED" |
# Res DB : TABLE:  "SYNONYMS" SCHEMA: | "SYNONYM" | "CURIE" |
# Pref DB : TABLE: "NAMES" SCHEMA: | "CURIE" | "NAME" | "CATEGORY" |
# Hash DB : TABLE: "HASHES" SCHEMA: | "HASH" | "CURIE" |
